RU_INPUT_UR_FAMILY_CATEGORY    = "Укажите ваш семейный статус:"
RU_ONLY_ONE                    = "Один субъект"
RU_PARENTS                     = "Семейная пара"
RU_SINGLE_PARENT               = "Родитель-одиночка"
RU_INPUT_UR_MONTHLY_IN_DOLLARS = "Укажите ваш ежемесячный доход (в долларах):"
